spring.application.name=demoShop
server.port=8081
server.address=127.0.0.1
server.servlet.context-path=/calc
logging.level.root=INFO
logging.level.com.student.calculator=DEBUG
string.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true