spring.application.name=demoShop
server.port=8081
server.address=0.0.0.0
logging.level.root=INFO
logging.level.com.student.calculator=DEBUG
string.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wadimlikar@gmail.com
spring.mail.password=axyc ckvu tomr nrfp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.to=wadimlikar@gmail.com
